words = [
["BMW","Volkswaagen"],
["Honda","Toyota"],
["Amazon","Facebook"],
["Tokopedia","Bukalapak"],
["Apple","Microsoft"],
["Starbucks","Kopimana"],
["Coca Cola","Pepsi"],
["Vietnam","Cambodia"],
["Italy","Spain"],
["Sweden","Finland"],
["India","Bangladesh"],
["Australia","New Zealand"],
["Japan","South Korea"],
["Mayonnaise","Ketchup"],
["Cake","Pie"],
["Taco","Burrito"],
["Pizza","Bagel"],
["Milkshake","Ice cream"],
["Salt","Pepper"],
["Doctor","Nurse"],
["Developer","Manager"],
["Designer","CEO"],
["Agent","Soldier"],
["Paris","Milan"],
["Walk","Run"],
["Golf","Tennis"],
["Yak","Bison"],
["Eagle","Dove"],
["Flamingo","Pelican"],
["Sheep","Ox"],
]